import { z } from 'zod';

/**
 * Canonical `dateRange` Zod schema for every tool that takes a date range.
 *
 * The shape is a UNION of three forms:
 *   1. A preset string from the Live-Reports / Slack picker, e.g. `'last_30_days'`
 *      — the most common runtime value, generated by `$REPORT_RANGE` substitution.
 *   2. The Live-Reports custom-range shape `{ start, end }` — what the date
 *      picker emits when the user picks an arbitrary window.
 *   3. The canonical `{ startDate, endDate }` shape — what the LLM sometimes
 *      emits directly when it knows the literal dates.
 *
 * Every tool that accepts a date range MUST use this schema (or a Zod-equivalent
 * derived from it) and call `normalizeDateRange()` to collapse the union into
 * `{ startDate, endDate }` before any logic runs. We've shipped the same bug
 * three separate times — Impact, Klaviyo, and gantri.sales_report — where a
 * tool's schema only accepted one of the shapes and `$REPORT_RANGE` failed
 * smoke validation. This module is the single source of truth so we never
 * have to fix it tool-by-tool again.
 *
 * **Adding a new tool with a date range?** Import `DateRangeArg` and
 * `normalizeDateRange` from here. There's a unit test in
 * `tests/unit/connectors/base/date-range-invariant.test.ts` that walks the
 * registry and validates every whitelisted tool's `dateRange` arg accepts
 * a preset string — it will fail your build if you regress.
 */

/** Preset names anchored on Pacific Time today. Adding a new preset?
 *  Update both this list and `presetToRange()` below. */
export const PT_PRESETS = [
  'today',
  'yesterday',
  'last_7_days',
  'last_14_days',
  'last_30_days',
  'last_60_days',
  'last_90_days',
  'last_180_days',
  'last_365_days',
  'this_week',
  'last_week',
  'this_month',
  'last_month',
  'month_to_date',
  'quarter_to_date',
  'year_to_date',
] as const;
export type PtPreset = (typeof PT_PRESETS)[number];

const Ymd = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'YYYY-MM-DD');

export const DateRangeArg = z.union([
  z.object({ startDate: Ymd, endDate: Ymd }),
  z.object({ start: Ymd, end: Ymd }),
  z.enum(PT_PRESETS),
]).describe(
  'Date range — accepts {startDate,endDate}, {start,end}, OR a preset string ' +
  '("last_7_days", "month_to_date", etc.). Live-Reports `$REPORT_RANGE` resolves ' +
  'to one of these three shapes; tools internally normalize to {startDate,endDate}.',
);
export type DateRangeArg = z.infer<typeof DateRangeArg>;

/** Pacific-Time today as `YYYY-MM-DD`. Used by every preset. */
export function ptToday(now: Date = new Date()): string {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Los_Angeles',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(now);
}

export function addDaysIso(ymd: string, n: number): string {
  const [y, m, d] = ymd.split('-').map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  dt.setUTCDate(dt.getUTCDate() + n);
  return dt.toISOString().slice(0, 10);
}

/** Resolve a preset name to a concrete `{ startDate, endDate }` window
 *  anchored on Pacific Time today. Throws on unknown preset (callers should
 *  rely on Zod to keep the input within `PT_PRESETS`). */
export function presetToRange(preset: PtPreset, today: string = ptToday()): { startDate: string; endDate: string } {
  switch (preset) {
    case 'today': return { startDate: today, endDate: today };
    case 'yesterday': { const y = addDaysIso(today, -1); return { startDate: y, endDate: y }; }
    case 'last_7_days': return { startDate: addDaysIso(today, -6), endDate: today };
    case 'last_14_days': return { startDate: addDaysIso(today, -13), endDate: today };
    case 'last_30_days': return { startDate: addDaysIso(today, -29), endDate: today };
    case 'last_60_days': return { startDate: addDaysIso(today, -59), endDate: today };
    case 'last_90_days': return { startDate: addDaysIso(today, -89), endDate: today };
    case 'last_180_days': return { startDate: addDaysIso(today, -179), endDate: today };
    case 'last_365_days': return { startDate: addDaysIso(today, -364), endDate: today };
    case 'this_week': {
      // ISO week: Monday → today
      const [y, m, d] = today.split('-').map(Number);
      const todayUtc = new Date(Date.UTC(y, m - 1, d));
      const dow = todayUtc.getUTCDay(); // 0 = Sun
      const daysSinceMonday = (dow + 6) % 7; // Mon=0, Sun=6
      const monday = addDaysIso(today, -daysSinceMonday);
      return { startDate: monday, endDate: today };
    }
    case 'last_week': {
      const [y, m, d] = today.split('-').map(Number);
      const todayUtc = new Date(Date.UTC(y, m - 1, d));
      const dow = todayUtc.getUTCDay();
      const daysSinceMonday = (dow + 6) % 7;
      const lastMonday = addDaysIso(today, -daysSinceMonday - 7);
      const lastSunday = addDaysIso(lastMonday, 6);
      return { startDate: lastMonday, endDate: lastSunday };
    }
    case 'this_month':
    case 'month_to_date': {
      const [y, m] = today.split('-');
      return { startDate: `${y}-${m}-01`, endDate: today };
    }
    case 'last_month': {
      const [yStr, mStr] = today.split('-');
      const y = Number(yStr);
      const m = Number(mStr);
      const lmY = m === 1 ? y - 1 : y;
      const lmM = m === 1 ? 12 : m - 1;
      const startDate = `${lmY}-${String(lmM).padStart(2, '0')}-01`;
      // Last day of last month = day before first of this month
      const lastDay = new Date(Date.UTC(y, m - 1, 0)).getUTCDate();
      const endDate = `${lmY}-${String(lmM).padStart(2, '0')}-${String(lastDay).padStart(2, '0')}`;
      return { startDate, endDate };
    }
    case 'quarter_to_date': {
      const [yStr, mStr] = today.split('-');
      const m = Number(mStr);
      const qStartMonth = Math.floor((m - 1) / 3) * 3 + 1;
      return { startDate: `${yStr}-${String(qStartMonth).padStart(2, '0')}-01`, endDate: today };
    }
    case 'year_to_date': {
      const [y] = today.split('-');
      return { startDate: `${y}-01-01`, endDate: today };
    }
  }
}

/** Collapse the three accepted DateRange shapes into the canonical
 *  `{ startDate, endDate }`. Pass `today` for deterministic test output. */
export function normalizeDateRange(input: DateRangeArg, today: string = ptToday()): { startDate: string; endDate: string } {
  if (typeof input === 'string') return presetToRange(input, today);
  if ('startDate' in input && 'endDate' in input) return { startDate: input.startDate, endDate: input.endDate };
  return { startDate: input.start, endDate: input.end };
}
