/**
 * Canonical introductory message DM'd to every newly-enabled user (and used
 * by `bot.broadcast_notification` when the caller asks for the standard intro).
 * Slack mrkdwn — single asterisks for bold, underscores for italics.
 *
 * Edit this string and redeploy to update what new users see.
 *
 * Voice rule: NEVER use internal system names ("Porter", "Transactions table",
 * etc.) in this message — most readers are non-technical. Real product names
 * users recognize (Northbeam, Klaviyo, Impact, GA4, Grafana) stay as-is.
 */
export const INTRO_MESSAGE = [
  'Hi team 👋',
  '',
  "I'm *Gantri Assistant*, the internal analytics assistant for Gantri. I live in Slack and answer questions about the business by pulling live data from Northbeam, Google Analytics 4, Klaviyo, Impact, Pipedrive, Google Search Console, our order system, and the Grafana dashboards — then I come back with the answer, with sources, in seconds.",
  '',
  'Think of me as the analyst you can ping at any hour without bothering anyone. No need to know SQL, no need to know which dashboard has what — just describe what you want.',
  '',
  '*The questions below are only a sample of what I can answer.* I support many more variations across all of these data sources, plus combinations between them. If something looks close to what you need, ask it your own way — and if you\'re not sure I can answer, just ask anyway. The worst that happens is I tell you I can\'t.',
  '',
  '---',
  '',
  '*📊 Marketing & Attribution* — Northbeam',
  '• _"What\'s our ROAS by channel last 7 days?"_',
  '• _"Compare native Meta ROAS vs Northbeam-attributed for April"_',
  '• _"Top 10 campaigns by revenue this month"_',
  '• _"LTV/CAC ratio per channel for Q1"_',
  '• _"Which Meta campaigns have the lowest marginal ROAS — I want to cut 20% of budget"_',
  '• _"% revenue from new vs returning customers per channel"_',
  '• _"Forecasted revenue at 30/60/90 days for Google Ads"_',
  '',
  '*📧 Email & SMS* — Klaviyo',
  '• _"Top email campaigns by revenue last 30 days"_',
  '• _"Open and click rate of our welcome series flow"_',
  '• _"How many subscribers in our engaged segment?"_',
  '• _"Which Klaviyo flows drove the most conversions in Q1?"_',
  '• _"Unsubscribe rate trend for the past 90 days"_',
  '',
  '*📥 Klaviyo profile management* — _admin / marketing roles only_',
  '',
  'If you have the *admin* or *marketing* role you can _write_ to Klaviyo straight from Slack — no need to switch to the Klaviyo UI:',
  '• *Add profiles inline by just asking* — for small batches (up to 20), paste or describe the people in chat. _"Add alice@x.com (Alice Anderson, +1 415 555 0101) and bob@y.com (Bob Brooks) to the Trade Show Leads list"_ works. I\'ll validate emails, ask which list (or _"no list"_), and subscribe them with email consent. No file needed.',
  '• *Bulk via CSV* — drop the file into your DM with me. I figure out the columns automatically — your headers don\'t have to match a fixed schema, just include something that looks like an email plus any of name / phone you have. I\'ll ask which list to put them in (or reply _"no list"_ to skip list-membership), then subscribe them with email consent. Files up to 1000 rows.',
  '• _"Create a Klaviyo list called BDNY 2026 Booth Leads"_ — fresh static list, ready to import into.',
  '• _"Delete these Klaviyo profiles: alice@x.com, bob@y.com"_ — always asks for confirmation first; up to 50 per call. Permanent — Klaviyo provides no undelete.',
  '• _"What\'s the status of the import I ran 10 minutes ago?"_ — audit trail with per-channel counts, list info, timestamps.',
  '',
  'Every write is audited (who, when, which list, how many) and I DM you when async jobs finish.',
  '',
  '*🤝 Affiliate Partners* — Impact',
  '• _"Top 10 Impact partners by revenue this quarter"_',
  '• _"Which partners had the most reversed actions last 90 days?"_',
  '• _"Per-conversion drilldown for Wirecutter last week"_',
  '• _"Compare Impact-attributed orders vs our actual orders for April"_',
  '',
  '*💼 Sales Pipeline* — Pipedrive (B2B Trade & Wholesale)',
  '• _"Show the funnel for our Made pipeline — count and value per stage"_',
  '• _"Top 15 organizations by won-deal value YTD 2026"_',
  '• _"Monthly won-deal trend across all pipelines for the last 12 months"_',
  '• _"Why did we lose deals last quarter?"_ — breakdown by lost reason',
  '• _"Sales rep leaderboard last 90 days by won revenue"_',
  '• _"Tell me about Rarify — open deals, contacts, last activity"_',
  '• _"Deal #816 in detail with all custom fields"_',
  '',
  '*✏️ Pipedrive lead capture* — _admin / marketing roles only_',
  '',
  'Marketing can write to Pipedrive directly from Slack — useful right after a trade show or a sales call:',
  '• _"Add Foo Studio as a lead — contact is jane@foostudio.com (Jane Doe), value $5k"_ — creates the lead with auto-resolved person + organization (reuses if they already exist).',
  '• _"Note on the Foo Studio lead: they want a custom matte black finish"_ — pin a free-form note to any lead/deal/person/org.',
  '• _"Remind me to follow up with Foo Studio next Tuesday at 3pm"_ — schedule a call/meeting/task with optional due date+time and assignee.',
  '• _"Delete that lead"_ / _"borra esa nota"_ / _"cancela esa tarea"_ / _"remove that organization"_ / _"borra ese contacto"_ — undo any lead, note, activity, organization, or person. I always show a preview and ask for *yes*; Pipedrive keeps deleted items in its recycle bin for ~30-90 days if you change your mind. Deals/leads attached to a deleted person/org stay (just unlinked).',
  '',
  'Every write is audited with the Slack user who triggered it.',
  '',
  '*🔎 Search Performance* — Google Search Console',
  '• _"Top 25 queries by clicks last 30 days for gantri.com"_',
  '• _"Pages with the biggest CTR drop comparing this month vs last"_',
  '• _"Average position by query for the past 90 days"_',
  '• _"Inspect indexing status of /products/wave-table-light"_',
  '',
  '*🌐 Site Behavior* — Google Analytics 4',
  '• _"Top 20 landing pages by sessions in April"_',
  '• _"Which product pages do users actually scroll all the way down?"_',
  '• _"How many active users are on gantri.com right now?"_',
  '• _"Add-to-cart rate by device this month"_',
  '• _"Top 30 events that fired last week"_',
  '',
  '*🏭 Orders & Operations*',
  '• _"How many late orders do we have right now?"_ — full per-order table with causes, deadlines, days past, notes',
  '• _"Did Hannah\'s order ship?"_ — by customer name or order ID',
  '• _"AOV for Trade orders this quarter, broken out by status"_',
  '• _"How many Wholesale orders shipped this month?"_',
  '',
  '*📈 Sales & Finance* — Grafana dashboards',
  '• _"Pull the Sales report for last week, broken out by transaction type"_',
  '• _"On-time delivery rate this month"_',
  '• _"Run the OKR dashboard for Q1"_',
  '• _"CSAT and NPS for the past 30 days"_',
  '',
  '*🔍 Cross-source comparisons*',
  '• _"Compare daily Northbeam-attributed orders vs our actual orders for the last 14 days"_',
  '• _"Why don\'t Northbeam and our orders match for January?"_ — I\'ll give you the exact order(s) that differ and why',
  '',
  '---',
  '',
  '*📑 Reports, canvases, and CSVs*',
  '',
  'Anything tabular, I deliver in the right format automatically:',
  '• Small breakdowns → inline in chat',
  '• Per-row tables → a *Slack Canvas* with the full data',
  '• Big exports (50+ rows) → CSV file attached',
  '• Just ask: _"open a canvas with the top 50 customers by lifetime value"_',
  '',
  '---',
  '',
  '*📊 Live Reports — shareable dashboards for the team*',
  '',
  'When a question would benefit from a stable URL the whole team can revisit (WTD vs prior weeks, late orders snapshot, channel-level attribution breakdown, email performance dashboard, etc.), I can publish it as a Live Report. The data refreshes on every visit, the URL is bookmarkable, and you can change the date range from the page.',
  '',
  '• _"Create a live report comparing this week\'s sales to the prior 2 weeks by transaction type"_',
  '• _"Live dashboard with our late orders, refresh every visit"_',
  '• _"Publish a live report of revenue and spend by channel — Cash snapshot, Clicks + Modeled Views"_',
  '• _"Live report of Klaviyo email performance — campaigns and flows"_',
  '• _"What live reports do I have?"_ — list all yours',
  '• _"Recompile the weekly sales report — change the breakdown to Forecast"_',
  '',
  'Each report lives at `reports.gantri.com/r/<slug>` — once you visit one, your browser is auto-authorized for 30 days, so bookmarking bare URLs and sharing them in Slack just works.',
  '',
  '---',
  '',
  '*📅 Recurring reports — set it once, get it forever*',
  '',
  'If a question is useful daily/weekly/monthly, subscribe to it instead of re-asking:',
  '• _"Send me Sales totals every Monday at 7am PT"_',
  '• _"Daily DM at 9am with Northbeam-attributed revenue by channel"_',
  '• _"Weekly late-orders report on Fridays at 4pm"_',
  '• _"Every Monday at 8am, send a CSV with all late Trade orders"_',
  '',
  'I compile each subscription into a deterministic plan once and the runner re-fires it on cron — same numbers every time, no drift. Manage them with: _"what reports do I have"_, _"unsubscribe from the daily sales report"_.',
  '',
  '---',
  '',
  '*💡 Feature requests — make me faster*',
  '',
  'If you find yourself asking the same question repeatedly and it takes me more than ~30 seconds to answer, *please tell me*. Send: _"feature request: [your ask]"_ and it goes straight to Danny. We build dedicated tools for those — they run in 1–2 seconds and the answer is always exact.',
  '',
  'Real examples we already built this way:',
  '• Late-orders report with cause analysis — was 45s, now 4s',
  '• Page-completion / scroll-depth analysis — used to time out, now 2s',
  '• Per-order diff between Northbeam and our order system, with cause classifier',
  '• Daily Northbeam-vs-orders side-by-side reconciliation, no manual joining',
  '• Klaviyo per-campaign and per-flow performance with attributed revenue',
  '• Klaviyo monthly subscribed-to-email-marketing event counts (live, ~500ms)',
  '• Impact per-partner performance with state breakdown (PENDING / APPROVED / REVERSED)',
  '• Pipedrive pipeline funnel + organization performance + lost-reason analysis (11 tools)',
  '• Search Console per-query / per-page performance with CTR / position trends',
  '',
  'The more you tell me what you ask, the sharper I get.',
  '',
  '---',
  '',
  '*✨ Worth knowing*',
  '• I cite sources on every answer (Northbeam, Klaviyo, Impact, Pipedrive, Search Console, GA4, Grafana, our order system).',
  '• If you spot a wrong number, reply _"that\'s wrong because…"_ and I\'ll log feedback for Danny.',
  '• I\'m allowlisted — only the leadership, marketing, and analytics teams can see me. Conversations are private DMs.',
  '• I cache results that won\'t change (closed-period attribution). Repeat questions come back near-instant.',
  '',
  'Just DM me. Try it now: _"how much did we spend on ads this week?"_ 🚀',
  '',
  '— Gantri Assistant',
].join('\n');
